config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new' # display rails form
  # post 'posts', to: 'posts#create'	# submit the form
  # get '/posts/:id/edit', to: 'post#edit'	# edit
  # patch '/posts/:id', to: 'posts@update'	# submit the edition

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end


    # collection do
    #   get :archives # GET /posts/archives
    # end

  	resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update]
end

# Option1:
# resources :votes, only: [:create]
# POST /votes => 'VotesController#create'
#   - needs two pieces of information

# Option2(which we use in the case):
# POST /posts/3/vote => 'PostdController#vote'
# POST /comments/4/vote => 'CommentsController#vote'

app/models/post.rb
class Post < ActiveRecord::Base
	include Voteable

	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories

	validates :title, presence: true, length: {minimum: 5}
	validates :url, presence: true, uniqueness: true
	validates :description, presence: true

	before_save :generate_slug

	def generate_slug
		self.slug = self.title.gsub(' ', '-').downcase
	end

	def to_param
		self.slug
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # There are two purpose for before_action
  # 1. set up something
  # 2. redirect away from action

  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]

  def index
  	@posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new

    # # exposing API
    # respond_to do |format|
    #   format.html{render json: @post}
    # end
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
    @post.creator = current_user

  	if @post.save
  		flash[:notice] = 'Your post was created.'
  		redirect_to posts_path
  	else # validation error, we can display error messages
  		render :new # which you submitted this action from
  	end
  end

	def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    # if @vote.valid?
    #   flash[:notice] = "Your vote was counted."
    # else
    #   flash[:error] = "You can only vote for <strong>that</strong> once.".html_safe
    # end

    # redirect_to :back

    respond_to do |format|
      format.html { redirect_to :back, notice: "Your vote was counted."}
      format.js
    end

  end

  private

	def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
		
    # if you require all the params, you can just simply type following
    # params.require(:post).permit!
	end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

end

app/views/posts/_form.html.erb
 <%= render 'shared/errors', obj: @post %>

<div class="well">
	<%= form_for @post do |f| %>
		<div class="control-group">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class="control-group">
			<%= f.label :url %>
			<%= f.text_field :url %>
		</div>
		<div class="control-group">
			<%= f.label :description %>
			<%= f.text_area :description, rows: 5 %>
		</div>

		<div class='control-group'>
			<%= f.label 'Categories' %>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
				<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
			<% end %>
		</div>

		<%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
	<div id="error_post_vote_<%= post.to_param %>" class='alert alert-error' style="display: none">
		You can only vote on a post once.
	</div>
	<div class= "span0 well text-center">
		<% if logged_in? %>
			<%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
				<i class="icon-arrow-up"></i>
			<% end %>
			<br/>
		<% end %>
		<span id="post_<%= post.id %>_votes"><%= post.total_votes.to_s + ' votes' %></span>
		<% if logged_in? %>
			<br/>
			<%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
				<i class="icon-arrow-down"></i>
			<% end %>
		<% end %>
	</div>
 	<div class="span8 well">
 		<%= render post.categories %>
 		<h4><%= link_to post.title, fix_url(post.url) %></h4>
 		<p><%= post.description %></p>
 		<p>
 			<span class="quiet">posted by </span><%= link_to post.creator.username, user_path(post.creator)%>
 			<small>at <%= display_datetime(post.created_at) %></small>
 		</p>
 		<small>
 			<span>
 				<%= link_to("#{post.comments.size} comments", post_path(post)) %>
 			</span>
 		</small>
 	</div>
 </div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<!-- <h3>Welcome!</h3>

<p>This is the Postit template. You've access the PostsController, index action. This is the index template. Find me under app/views/posts folder.</p>
 -->

 <!-- <h4>All posts!</h4>

 <ul>
 	<% @posts.each do |post| %>
 		<li><%= link_to post.title, post_path(post) %>(<%= link_to 'edit', edit_post_path(post) %>)</li>
 	<% end %>
 </ul> -->

<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
	<%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<!-- <h4>Pure HTML form</h4>
<form action='/posts' method='POST' >
	Title: <input type='text' name='my_title'/>
	</br>
	<input type ='submit' class='btn btn-primary'>
</form>

<h4>Rails form helpers</h4>
<%= form_tag '/posts' do %>
	<%= label_tag :title %>
	<%= text_field_tag :title %>
	</br>
	<%= submit_tag 'Create Post', class: 'btn btn-primary' %>
<% end %>
 -->


 <!-- Rails model-backed form helpers -->
<!-- <h4>Create a post</h4> -->
<!-- 
<% if @post.errors.any? %>
	<div class='alert alert-error'>
		<h5>There were some errors:</h5>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	</br>
	<%= f.label :url %>
	<%= f.text_field :url %>
	</br>
	<%= f.submit 'Create Post', class: 'btn btn-primary' %>
<% end %> -->

<!-- <%= render 'form' %> -->

<!-- -------------------------------------------------------------------- -->

<%= render 'shared/content_title', title: 'Create a new post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<!-- <h4>Hi there, you're viewing <%= @post.title %></h4>

<%= link_to 'go back to all posts', posts_path %>

<h5>Create a comment:</h5>
<%= form_for [@post, @comment] do |f| %>
	<%= f.text_area :body %>
	</br>
	<%= f.submit "Create Comment", class: "btn btn-primary" %>
<% end %> -->

<% if logged_in? && (@post.creator == current_user || current_user.admin?) %>
	<p class= 'pull-right'>
		[<%= link_to 'edit this post', edit_post_path(@post) %>] 
	</p>
<% end %>

<p>
	<%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
<%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
	<%= form_for [@post, @comment] do |f| %>
		<%= render 'shared/errors', obj: @comment %>
		<div class="control-group">
			<%= f.label :body, 'Leave a comment' %>
			<%= f.text_area :body, rows: 3, class: 'span4' %>
		</div>
		<%= f.submit 'Create Comment', class: 'btn btn-primary' %>
	<% end %>
<% end %>

<h5>Comments:</h5>
<% @post.comments.each do |comment| %>
	<%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$('#post_<%= @post.id %>_votes').html('<%= @post.total_votes %> votes');
<% else %>
  alert("You can only vote on a post once.");
  // $('#error_post_vote_<%= @post.to_param %>').show();
<% end %>